INSERT INTO public.videogiochi(titolo, produttore, img_path, prezzo, qta, console, descrizione)
	VALUES
		('FIFA 19', 'Electronic Arts', 'media\fifa19.jpg', 29.99, 10, 'PS4',
		'Grazie al motore Frostbite™, EA SPORTS™ FIFA 19 offre un''esperienza da campioni, dentro e fuori dal campo. Con l''aggiunta della prestigiosa UEFA Champions League, FIFA 19 offre funzionalità di gioco migliorate che ti permettono di controllare tutto ciò che avviene in campo in qualsiasi momento, garantendoti una libertà d''azione senza precedenti. Include l''emozionante finale della storia di Alex Hunter con Il Viaggio: Campioni*, una nuova modalità all''interno dell''ormai popolarissimo FIFA Ultimate Team™, e molto altro ancora. FIFA 19 ti permette di giocare ai più importanti tornei per club, grazie a una serie di modalità su licenza che comprendono la UEFA Champions League, la UEFA Europa League e la UEFA Super Cup. Modalità: La UEFA Champions League, la UEFA Europa League e la UEFA Super Cup prendono vita in EA SPORTS FIFA 19. Dalla rincorsa al titolo ne Il Viaggio: Campioni, agli aggiornamenti live in FIFA 19 Ultimate Team, dall''integrazione autentica nelle modalità Calcio di inizio e Carriera, fino alla nuova modalità Champions League, potrai vivere la più grande competizione calcistica per club al mondo in FIFA 19.  Modalità Champions League: Vivi tutte le emozioni del torneo ufficiale della UEFA Champions League, dalla fase a gironi fino alla gloriosa finale. O gioca una versione personalizzata del torneo con un club europeo a tua scelta. Elementi ufficiali UEFA: Lasciati coinvolgere dai tornei per club più prestigiosi d''Europa con le grafiche televisive, le divise, gli stemmi, i palloni e i trofei ufficiali della UEFA Champions League, UEFA Europa League e UEFA Super Cup.'
		),
		('FIFA 19', 'Electronic Arts', 'media\fifa19.jpg', 29.99, 10, 'XBOX ONE',
		'Grazie al motore Frostbite™, EA SPORTS™ FIFA 19 offre un''esperienza da campioni, dentro e fuori dal campo. Con l''aggiunta della prestigiosa UEFA Champions League, FIFA 19 offre funzionalità di gioco migliorate che ti permettono di controllare tutto ciò che avviene in campo in qualsiasi momento, garantendoti una libertà d''azione senza precedenti. Include l''emozionante finale della storia di Alex Hunter con Il Viaggio: Campioni*, una nuova modalità all''interno dell''ormai popolarissimo FIFA Ultimate Team™, e molto altro ancora. FIFA 19 ti permette di giocare ai più importanti tornei per club, grazie a una serie di modalità su licenza che comprendono la UEFA Champions League, la UEFA Europa League e la UEFA Super Cup. Modalità: La UEFA Champions League, la UEFA Europa League e la UEFA Super Cup prendono vita in EA SPORTS FIFA 19. Dalla rincorsa al titolo ne Il Viaggio: Campioni, agli aggiornamenti live in FIFA 19 Ultimate Team, dall''integrazione autentica nelle modalità Calcio di inizio e Carriera, fino alla nuova modalità Champions League, potrai vivere la più grande competizione calcistica per club al mondo in FIFA 19.  Modalità Champions League: Vivi tutte le emozioni del torneo ufficiale della UEFA Champions League, dalla fase a gironi fino alla gloriosa finale. O gioca una versione personalizzata del torneo con un club europeo a tua scelta. Elementi ufficiali UEFA: Lasciati coinvolgere dai tornei per club più prestigiosi d''Europa con le grafiche televisive, le divise, gli stemmi, i palloni e i trofei ufficiali della UEFA Champions League, UEFA Europa League e UEFA Super Cup.'
		),
		('FIFA 19', 'Electronic Arts', 'media\fifa19.jpg', 24.99, 10, 'PC',
		'Grazie al motore Frostbite™, EA SPORTS™ FIFA 19 offre un''esperienza da campioni, dentro e fuori dal campo. Con l''aggiunta della prestigiosa UEFA Champions League, FIFA 19 offre funzionalità di gioco migliorate che ti permettono di controllare tutto ciò che avviene in campo in qualsiasi momento, garantendoti una libertà d''azione senza precedenti. Include l''emozionante finale della storia di Alex Hunter con Il Viaggio: Campioni*, una nuova modalità all''interno dell''ormai popolarissimo FIFA Ultimate Team™, e molto altro ancora. FIFA 19 ti permette di giocare ai più importanti tornei per club, grazie a una serie di modalità su licenza che comprendono la UEFA Champions League, la UEFA Europa League e la UEFA Super Cup. Modalità: La UEFA Champions League, la UEFA Europa League e la UEFA Super Cup prendono vita in EA SPORTS FIFA 19. Dalla rincorsa al titolo ne Il Viaggio: Campioni, agli aggiornamenti live in FIFA 19 Ultimate Team, dall''integrazione autentica nelle modalità Calcio di inizio e Carriera, fino alla nuova modalità Champions League, potrai vivere la più grande competizione calcistica per club al mondo in FIFA 19.  Modalità Champions League: Vivi tutte le emozioni del torneo ufficiale della UEFA Champions League, dalla fase a gironi fino alla gloriosa finale. O gioca una versione personalizzata del torneo con un club europeo a tua scelta. Elementi ufficiali UEFA: Lasciati coinvolgere dai tornei per club più prestigiosi d''Europa con le grafiche televisive, le divise, gli stemmi, i palloni e i trofei ufficiali della UEFA Champions League, UEFA Europa League e UEFA Super Cup.'
		),
		('Assassin''s Creed Odyssey', 'Ubisoft', 'media\ac_odyssey.jpg', 39.99, 10, 'PS4',
			'Forgia il tuo destino in Assassin''s Creed Odyssey. Vivi una vera e propria odissea per svelare i segreti del tuo passato, cambia il destino dell''antica Grecia e diventa una leggenda vivente. ESPLORA L''ANTICA GRECIA Attraversa rigogliose foreste, isole vulcaniche e vivaci città imbarcandoti in un viaggio ricco di scoperte e incontri in giro per un mondo in guerra plasmato da uomini e dèi. SCRIVI LA TUA LEGGENDA Ogni tua decisione influenzerà lo svolgimento del tuo viaggio. Scopri finali alternativi grazie al nuovo sistema di dialoghi e alle scelte che dovrai compiere. Personalizza la tua nave, l''attrezzatura e abilità speciali per diventare una leggenda. UNA NUOVA DIMENSIONE DI COMBATTIMENTO Dimostra le tue abilità in combattimento in battaglie su larga scala tra Atene e Sparta con centinaia di soldati, o manda a picco intere flotte in spettacolari battaglie navali nel Mar Egeo.'
		),
		('Assassin''s Creed Odyssey', 'Ubisoft', 'media\ac_odyssey.jpg', 39.99, 10, 'XBOX ONE',
			'Forgia il tuo destino in Assassin''s Creed Odyssey. Vivi una vera e propria odissea per svelare i segreti del tuo passato, cambia il destino dell''antica Grecia e diventa una leggenda vivente. ESPLORA L''ANTICA GRECIA Attraversa rigogliose foreste, isole vulcaniche e vivaci città imbarcandoti in un viaggio ricco di scoperte e incontri in giro per un mondo in guerra plasmato da uomini e dèi. SCRIVI LA TUA LEGGENDA Ogni tua decisione influenzerà lo svolgimento del tuo viaggio. Scopri finali alternativi grazie al nuovo sistema di dialoghi e alle scelte che dovrai compiere. Personalizza la tua nave, l''attrezzatura e abilità speciali per diventare una leggenda. UNA NUOVA DIMENSIONE DI COMBATTIMENTO Dimostra le tue abilità in combattimento in battaglie su larga scala tra Atene e Sparta con centinaia di soldati, o manda a picco intere flotte in spettacolari battaglie navali nel Mar Egeo.'
		),
		('Assassin''s Creed Odyssey', 'Ubisoft', 'media\ac_odyssey.jpg', 29.99, 10, 'PC',
			'Forgia il tuo destino in Assassin''s Creed Odyssey. Vivi una vera e propria odissea per svelare i segreti del tuo passato, cambia il destino dell''antica Grecia e diventa una leggenda vivente. ESPLORA L''ANTICA GRECIA Attraversa rigogliose foreste, isole vulcaniche e vivaci città imbarcandoti in un viaggio ricco di scoperte e incontri in giro per un mondo in guerra plasmato da uomini e dèi. SCRIVI LA TUA LEGGENDA Ogni tua decisione influenzerà lo svolgimento del tuo viaggio. Scopri finali alternativi grazie al nuovo sistema di dialoghi e alle scelte che dovrai compiere. Personalizza la tua nave, l''attrezzatura e abilità speciali per diventare una leggenda. UNA NUOVA DIMENSIONE DI COMBATTIMENTO Dimostra le tue abilità in combattimento in battaglie su larga scala tra Atene e Sparta con centinaia di soldati, o manda a picco intere flotte in spettacolari battaglie navali nel Mar Egeo.'
		),
		('Star Wars Battlefront II', 'Electronic Arts', 'media\battlefront2.jpg', 24.99, 20, 'PS4',
			'Preparati a tornare sul fronte della battaglia nel nuovo episodio della serie di Star Wars in alta definizione più venduta di sempre. Diventa l''eroe e combatti nei panni di un intrepido soldato, pilota un leggendario caccia stellare, controlla il tuo personaggio di Star Wars preferito o segui le gesta di un soldato scelto delle forze speciali in una nuova e appassionante storia di Star Wars.'
		),
		('Star Wars Battlefront II', 'Electronic Arts', 'media\battlefront2.jpg', 24.99, 20, 'XBOX ONE',
			'Preparati a tornare sul fronte della battaglia nel nuovo episodio della serie di Star Wars in alta definizione più venduta di sempre. Diventa l''eroe e combatti nei panni di un intrepido soldato, pilota un leggendario caccia stellare, controlla il tuo personaggio di Star Wars preferito o segui le gesta di un soldato scelto delle forze speciali in una nuova e appassionante storia di Star Wars.'
		),
		('Star Wars Battlefront II', 'Electronic Arts', 'media\battlefront2.jpg', 19.99, 20, 'PC',
			'Preparati a tornare sul fronte della battaglia nel nuovo episodio della serie di Star Wars in alta definizione più venduta di sempre. Diventa l''eroe e combatti nei panni di un intrepido soldato, pilota un leggendario caccia stellare, controlla il tuo personaggio di Star Wars preferito o segui le gesta di un soldato scelto delle forze speciali in una nuova e appassionante storia di Star Wars.'
		),
		('The Division 2', 'Ubisoft', 'media\the_division2.jpg', 14.99, 15, 'PS4',
		'Sono trascorsi sette mesi da quando un virus letale ha colpito la città di New York e il resto del mondo, decimando la popolazione. Quando il virus si è diffuso, è stata attivata come ultima linea difensiva la Divisione, un''unità dormiente di agenti civili. Da allora, gli agenti della Divisione hanno combattuto senza sosta per salvare ciò che restava della civiltà. Per la Divisione, la posta in gioco è più alta che mai, poiché il mondo è sull''orlo del collasso. Washington, D.C. è in serio pericolo e se dovesse cadere, anche l''intera nazione sarà spacciata. Come agente della Divisione che ha operato sul campo negli ultimi sette mesi, tu e la tua squadra siete l''ultima speranza per arrestare la distruzione della società dopo la diffusione dell''epidemia.'
		),
		('The Division 2', 'Ubisoft', 'media\the_division2.jpg', 19.99, 15, 'XBOX ONE',
		'Sono trascorsi sette mesi da quando un virus letale ha colpito la città di New York e il resto del mondo, decimando la popolazione. Quando il virus si è diffuso, è stata attivata come ultima linea difensiva la Divisione, un''unità dormiente di agenti civili. Da allora, gli agenti della Divisione hanno combattuto senza sosta per salvare ciò che restava della civiltà. Per la Divisione, la posta in gioco è più alta che mai, poiché il mondo è sull''orlo del collasso. Washington, D.C. è in serio pericolo e se dovesse cadere, anche l''intera nazione sarà spacciata. Come agente della Divisione che ha operato sul campo negli ultimi sette mesi, tu e la tua squadra siete l''ultima speranza per arrestare la distruzione della società dopo la diffusione dell''epidemia.'
		),
		('The Division 2', 'Ubisoft', 'media\the_division2.jpg', 9.99, 15, 'PC',
		'Sono trascorsi sette mesi da quando un virus letale ha colpito la città di New York e il resto del mondo, decimando la popolazione. Quando il virus si è diffuso, è stata attivata come ultima linea difensiva la Divisione, un''unità dormiente di agenti civili. Da allora, gli agenti della Divisione hanno combattuto senza sosta per salvare ciò che restava della civiltà. Per la Divisione, la posta in gioco è più alta che mai, poiché il mondo è sull''orlo del collasso. Washington, D.C. è in serio pericolo e se dovesse cadere, anche l''intera nazione sarà spacciata. Come agente della Divisione che ha operato sul campo negli ultimi sette mesi, tu e la tua squadra siete l''ultima speranza per arrestare la distruzione della società dopo la diffusione dell''epidemia.'
		);
